hash-format = "sha256"

[[files]]
file = "README.md"
hash = "ddd1b449d32f26c4be2d6daf0ad8410db2dd5b56b7191149a2a0ce0095cea87d"

[[files]]
file = "gitattributes"
hash = "f1c49afdbf5c184940b9d1b0dcb6e070c8ca915a36d6c2b7f5a4c641e1080aea"

[[files]]
file = "gitignore"
hash = "eb49facfdd2488fd2fa583f1bce654899ce74b6c92621a42fc38facd62a9da31"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1fc1e482945dff68e6aab34b22d61d054a6177869408ed4af3fef6117a33faab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "659f7b849f370718cc5216c3de0fdc4863391f9889d00ebd4ccef8274ee7026d"
metafile = true

[[files]]
file = "mods/better-serversleep.pw.toml"
hash = "bcd288645aa1b05e2f408aac5680f55cf0d648da7dcc67a063b05220ccf1c200"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "59658f3b9d3b86b24440008fd2031c53d538cbb35e84524bcdbc67f0de7ea251"
metafile = true

[[files]]
file = "mods/blossomhomes.pw.toml"
hash = "792db6eb097b3731d24c1888723ffcfd7914cec6b969f103a672cc7504cfe3b3"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "06f14238b158016b8832fbc2cd7e9730a58ef475fc74359031a4f4f8cba1340f"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "6d717e11f5a11194004d8879b5c1e46448394855211ce8ac1937ae40895f2c27"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "4ee1808a7fb319d469dece5752cedb05dacb9afbe48021fa664f54b8c83fdc45"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "6083db761c82eece49adba0b0cee0b37068422e2eb170b7039ebae65972d03e1"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "783d509d7069d90ca34641f64936fc0eba7b974f0209e40a7ce915e4436e3309"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3d24d58b2caf4fd73d76b2d734a1d06490994d5d38177376e6f5d8d9f8fb87e0"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "b152c75412428e5f53667cb0836fa1323ca93cbd925e456239710a2e261d9963"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "fe04f0d6db074548db155c4863bd812b40b95dc3a3bc041d2f25d244674cdd59"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "716b671d0b15ea17c788c571620eac83207bb2b6e8dbe0d33319838478f21efc"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "e82e55f18e637d969caa89a0abd5e1ac72b1de18a7299f6a698959b6fca7388a"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "2c70a5c7fe3645b0e297fef8b9b091666e96c0b362d984918ed22df94464f2f0"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
hash = "3a4add64a54b7d4df688fc0f58872bf130ffeb7a6016a5e59d009f7317810c82"
metafile = true

[[files]]
file = "mods/elytra-trinket-updated.pw.toml"
hash = "21c5020ddcfc33195148b222e3f6bb1613b3e9d86543f13b66a93470ad76913d"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d74f72f3bf13c4ef7d60b6e2defecd3c7af77ed9be7764cf1ed10ea1fd707a1f"
metafile = true

[[files]]
file = "mods/grimac.pw.toml"
hash = "ccc016081b9d6559b5c921a02151b8113db0a1c15a0a09983e61086ab41c2b8a"
metafile = true

[[files]]
file = "mods/hidearmormod.pw.toml"
hash = "7dd8af2ed6f9e72d6c9045bc7772a793c010a83ba606d264caf630b3d4442cc0"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5a6ee9ae2de75743aa027eb753ac9c3cb92305df67bde8fe2cefdd2df0eb49d7"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "7f5ae343f4e9e6e49c723311892b02351ff8031b2c3a1bf3d0e700bcd996ce90"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "b0366239de9d38bb6162e37b2bfd77a136732d35bc8e79688f4cffc18de17f70"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "bdca3c9a098de3c08f996b214cf10ece27351f5f7871c30ff826a2f404daba33"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "7c9ed8db12a2bfd5bdcb6c3060ff9081dc65991e7e20defd2f0215faec25f5ce"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "b9eadbeac742be0f77b95d3067c4760347452b690b8ae00268f4d5edc7ee8e70"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "6768436aae94ac92d1ecd91d1601d4b34b6fe618b2292855151b3b5c382d9eac"
metafile = true

[[files]]
file = "mods/ly-graves.pw.toml"
hash = "20779e1962b9197eef99054d1ac63b1b82c1a92c23e3d05b425b5f9cf9e002a3"
metafile = true

[[files]]
file = "mods/minecraft_autotools.pw.toml"
hash = "d573dfdb3d44d671290aabfa6d3bea747c75ba2ba9d9c9e659c72d2cbedb5a23"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "b261880bd245c83c51b729199452da12b0766a4aa0210fc79d0c48161cbfcc49"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/name-tag-tweaks.pw.toml"
hash = "b82596c98473c661b1a4551ac430aaff36a5e391d8d92979faaa472f97abc0aa"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "a533c05d98c59436819e9c801198a989c6ff55133c95281ea7f8d28a71e23777"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "d788235233cd7bb10444760f354161d730ce1c504976cfdf91bd26fcd05c9e26"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "84cb0dcad9ac46d22adba4fb7924951affa6ac5e46027a3b25fa9a0db8d91b2b"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "22a83a04b4df87ab4bbea18228c3cc695551610c66cc79ccc315d783d3f7848f"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "42a73228a2e7ddd0a2ebba1e2a03dec5dbf4605854ec89c05f7e1374baffeae5"
metafile = true

[[files]]
file = "mods/serverbacksnow.pw.toml"
hash = "45b0ef25293813e21fc48e7e554890936eb2c054ff53376129e64c3995b3cf62"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c9fd548aa345384fe05cc143a191e6e507a07c20a08f31562966f5423a4e39d9"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "493a76add332abb0dfa23004300ea2ae77a8448960f603519c1db5ab4d769413"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "bb7064282571976ed2bbe266bcf5e525d6d661aeea89649e4d604327973cf92d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "1e78d593cf4ee1fca22780db53353b59ac36f718efbfb379f99e3cdf010f408c"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "831c41448bccb5bb8f1f68a76321e7da7988b218e9694f432d952f98ac184640"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "52ac59a01a3eb32b0ee2620bd26d8d0c4dda9eb49877aaa2c14dcbbfd2ca0374"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "e9302f39fb02c0a1f88893785d54b08e41a17c9fb3e39c29c3794e7ed7f86bad"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "7b976155d02000a064de326c3918686bc8be05125a16570659c5f5c9feab768b"
metafile = true

[[files]]
file = "mods/trinkets-canary.pw.toml"
hash = "d46a8d72f489c2d8d7ccea5c9ae7d871b4b1ec9ff2dc8eef613710adf76c8209"
metafile = true

[[files]]
file = "mods/tslatentitystatus.pw.toml"
hash = "1e2d1da19f08a4b1e9a4b19ecf9cf812eb31a62754a31d60dce3b5146521e107"
metafile = true

[[files]]
file = "mods/undead-leather.pw.toml"
hash = "e40263983c7dd10236bf6e23eb439f08d91a038b8ec0473f5e53213137ca3ceb"
metafile = true

[[files]]
file = "mods/vanilla-refresh.pw.toml"
hash = "c747d8ec64328f2722166ac62ea371cd5becf82fa4b8012a679092649046f5b4"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "5cb9a93032a75644cdf442b05a29e0616c76df503ee6b3dd3ab367ad1a04ff60"
metafile = true

[[files]]
file = "mods/xaero-zoomout.pw.toml"
hash = "896dc18c8839f179aca6e9a7891de85898a4f5814a35249781d3efda33d29091"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "993390d4661a77aa83c8416f75addfccaf7cee0a7a7311a21742b2036700b5ac"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "53c8bc02c9b10610c43fc29127039036217e33a95ab2ea2d6ac291987266ef89"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfa4ddfc8999e7be331c6dad1f2a0372f996243241d21697939e6838b3402c6d"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "packwiz-installer.jar"
hash = "c9f646908d340d84773948a9a7d98bc1dae250d35e1016dc6e2b8459760b5598"

[[files]]
file = "packwizignore"
hash = "9f6edd634b0cac9086f9aa22c96880b7552d7cc6a95128df9f79578a080d2daa"
