hash-format = "sha256"

[[files]]
file = "README.md"
hash = "ddd1b449d32f26c4be2d6daf0ad8410db2dd5b56b7191149a2a0ce0095cea87d"

[[files]]
file = "gitattributes"
hash = "f1c49afdbf5c184940b9d1b0dcb6e070c8ca915a36d6c2b7f5a4c641e1080aea"

[[files]]
file = "gitignore"
hash = "615471c0958030fcd69310a182346ad2f0228a924b86c8c82297efeb45b89470"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "73b2408a4e00098cf7a97455fe493949808ae1a138c49bec088cbd3c750d6a51"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "3865066c1369948d5342313e2f4d6f517104d2c57680150139745075b46c6d85"
metafile = true

[[files]]
file = "mods/better-serversleep.pw.toml"
hash = "b3a838ce9dc2fbd5a5ef9e42dddc4e573ca0adda0c669a992bfce4bdafe781de"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "eca7a9bd578b6eaccc262f7f3f2ba757f7ef1c76d3ea50d059df66341a4ab433"
metafile = true

[[files]]
file = "mods/blossomhomes.pw.toml"
hash = "843339ab886b514a321d57e35d9baa08c91696a5510c205fb768f6ee6e7f920e"
metafile = true

[[files]]
file = "mods/blossomlib.pw.toml"
hash = "991670dec329214074702bb3dd44200f77fad3c2cf5b35b98b4feb79d345de61"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "b507f3aff8642f0f6a4e1bd335c821da18a591875cf589c21f3552e19e7418b9"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "c0b60e2f1bf23247c6216c2f850b1369d31165284803513efda4f77012dc310b"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "57700df4d96da20363a2a26efa0f25d6c6aed441e29788439505985d8263e05d"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "c63c03b6d7ba8be09a1cb191b0624c42ce4c2c637ad4033e936940cf4cf3af34"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "47cb2d64a12e141e11ce5a211d9036a23c41698e3ea7de5dc8f4fd08638b2694"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "13efe435aac427c36c5ba49e4b545a6bfcee01f532811805222186d29f20dec7"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "00a580fef083d6cc9dd669bbb147757331af55077323129df92884ee153e09f3"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "71a29a32ec3722068dcff5496313d3d084263f27e48634f02418b2f3028cf0a8"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "e1879d997a12a832043c0380df086748a51de9688718bfa9c323e68520014858"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "8ae5f83ee7208dce425d107dee059919ee120ffb3ea72cb34f243253a2fd11b9"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "40cd28ee0012a938d0bd8dedf94f44bc7890d69c6a824597197e30f26f8b229e"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "935a139a561f13de2c791e87647f41a14e3e6f7ab2a1f7e8f24ded5832081e10"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
hash = "3a635e8e309bd25fa69af0e5371d9691eb368f0fc9b8e9d69aa7ebd6d00f7cc6"
metafile = true

[[files]]
file = "mods/elytra-trinket-updated.pw.toml"
hash = "b00da39ad625418b30fd30df79e1933483a8a0307d5d93956c366a45ae13a3d7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cc8fd3989b8d0234f4ff40de29f0e32ac838aaf87f6669bfc5edfb88a3f00f7b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "7f53b315580609c3da12ae3338d201003eb54dfaf5dd6e1d4dafb168c8bda1f5"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "691cea763cfcd4625c3b7af109acba96289ade9cfe0008510f05dc4abf98eb50"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "59763290be9efedece6960fa2d4afb42cd10776a9ed73ceec786391154462947"
metafile = true

[[files]]
file = "mods/grimac.pw.toml"
hash = "30b06f7ba480d91552434e506569e5b18354a3144e0f22b610c7a567da0d8079"
metafile = true

[[files]]
file = "mods/hidearmormod.pw.toml"
hash = "aadf93cce31a057bf8d94a10b5c193e1f0200a688c74f8252df39756f0a156e0"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "aba4a61f1de5a7ded06a2e35638fad59fd69c8f4a9196bc9229f456eef997e89"
metafile = true

[[files]]
file = "mods/immersive-ui.pw.toml"
hash = "7b7a9b307b97887fc703c78c1cd224620ea2267b02d0230156f5b519f6d66dc4"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "dd1d882847403837479abe2a29e99da52667fe7a413927983fcd17e584708ab7"
metafile = true

[[files]]
file = "mods/inventoryhudplus.pw.toml"
hash = "e58b6b6a6252cb5fde0a79cff61c723ce3853c80783d8c545a9fb693c2cf33d8"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "050dffe59c61ded3b3e474cc24c11496d14739ddd3a0efc2ceda22652865eaa7"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "9cb532266fde62c5b339d63ca1d0b1f00e94bb85de032158692187a85126e12d"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "baa7f1d14c7afba9702e3a3f485a8c96acc8a50fca5a11e6f8a3d25ce109ec9d"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b007afbcbec7f67e1355be0429cf10b0891ffd98f087388e9802319fcd5b1559"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "ee8cbde93306796c1a4a3535672b364c27a1eebd75185838c7961cc2895027a0"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "f3e3d64ba54db8bb47a5356ff3a1a750dfbf27b535878a13e2102b9da2eede6d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "45957cf6ae9def414ae6d1abcc91d97e054e8a3c59bf79f8a40644b9f8e0e09b"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "53285961b5a53cd18db6b3b99dd5b973412959fac277c6811bffcd69a7b8e8ea"
metafile = true

[[files]]
file = "mods/ly-graves.pw.toml"
hash = "5e1223bf790cfacbab7a3b8180bc8793463e7b438fecc3ea6358eb218d704601"
metafile = true

[[files]]
file = "mods/minecraft_autotools.pw.toml"
hash = "5f7e68c03593fec5b89d01b19a4c54ecdd70d001d55c200f60b770d45f045f00"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "467d8f5e030f1d26bea595c7a73163f27a3e4c832395660bcdd156f3994e85e4"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "a91d68c3ac5b08bd79e32dd9f3335fc9a9763afeb7602492cd159351704fccc6"
metafile = true

[[files]]
file = "mods/name-tag-tweaks.pw.toml"
hash = "62c55641d18709c9834632688691ad5ebd2aed3053dbb860221f802435bb81b8"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e01e4e296bff245a222574cb664cdf07d934356c0de81c6a9ac32a1c9bd25cb2"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "b1a44adca30f780ec0dd672a47ce48cc02aa229a17d0763b5518d6cf7adb6da4"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "c31ac8502e4e5ab7f98771e0d7bcff693f7edb0ba9da3c8877bd6e7aecb82827"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "2bd7d809b26695322625b7db762ff61bf27c76b74840bb6be532f88c24854f44"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
hash = "256f90ac749470d31f840935002838c49d21bc515d3f9fa9e9dfb987763618aa"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "da8027302e071db16b21c4abf1ab8f04245b283c4f44a3fdf98dc1e4c6d2d585"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "6b78e9f4bc15311bc973938ceadc6896b8aa332fa70cb41d9939b502654ca23d"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "fd39726cf95a2cb1cd3f92c59556e9070cee3738ecfaaa51fed9642455cc6fba"
metafile = true

[[files]]
file = "mods/serverbacksnow.pw.toml"
hash = "62075f28131f760acddbc9783e02b748196e2fd0583f1f595dfa23ada40e2ae8"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "c07dff3c89db61bba621dbfa59245bee06dfdcacc90a024e93da797df73290a9"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "ba8bae91375a361a50c6a26f6832bdb9bbe780189f29c7b328fcbf288e4b7a54"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "69f8726c1cf2e486d166a40dc253d01eade959d21b429cf7e7c413861a3c2ec0"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "7caca0627faddce5ea61f7e8ceadb4d5e63ca4cc661c2b810ac1a5e937fb3c29"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "df9144262058897c8f5b0e1fa4c1dbf7eb43f427a63bfa89211516099a31ee68"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "5c7435f2a63d49538bd62decf3c801eef84593e540a500b496bd641b98e5ad66"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "dd7b7b3e21d419dbe6997c1573952a7ea22d81ddc5541c068e386908b97f7e46"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "e0fbb624ed0169199e158590a6b295a51aba55ca0cfbdcde9d3e34c36b12eb3d"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "b19248f530f6aa882ecaa18a47110adf782ac6a83036905947017cae6c07b052"
metafile = true

[[files]]
file = "mods/trinkets-canary.pw.toml"
hash = "9c45287b768d05e116e24db22e1ae0d949d841317f135dd8a9b4189c981b9ba4"
metafile = true

[[files]]
file = "mods/trinkets-polymer.pw.toml"
hash = "0ac6c5a491f4b832a87f3f3fd4926d2a3134bc23a4238b925c52b363a2065bf3"
metafile = true

[[files]]
file = "mods/tslatentitystatus.pw.toml"
hash = "9ef53ca839d8cfa375c5261ae777cc2f4511317e1b918a76be6d55a51ab467d4"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
hash = "2b7eccbc2fb51a5d6cbdd030540560b4bda64e34955c6db90a5a2cacb5c6c141"
metafile = true

[[files]]
file = "mods/undead-leather.pw.toml"
hash = "719eba0483a93f3a83b49d82edb85294e2d5c6133f26d6e53e5f1ff45c61de85"
metafile = true

[[files]]
file = "mods/vanilla-refresh.pw.toml"
hash = "bf04b3696b945e13209abdb082990e6e1aec9d99fd4bbe37d1b65b5fb6ff1a7f"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "7f0cec7802051eb21572be08ec1ad793d17512ee5562af1b37864afd8c01433d"
metafile = true

[[files]]
file = "mods/xaero-zoomout.pw.toml"
hash = "5cc2bd71c7ad0ad22761a32753ee27e2d7c13f9f9b3466e8f8d595d246e2cd76"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "452788e115a42ef60be9ea45f5324f037faf439a156118c35af194f83aaa1df2"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "90944bf4f9a7ae8e060116945029eac333b8c8561d342ff654950eda8983e9ef"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "45f81bda993af1f0a9d418dda93aacbda4bf2ea56f77a9d2845c3536ca630c52"
metafile = true

[[files]]
file = "packwizignore"
hash = "b85d9f4c68a66b28d9f0a16e17b72e6638d55c0c78a97e60ac5c38febba7bae6"
