name = "lewsicraft-modpack"
author = "Noemi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fca74eb70376d2a9745fc9ee4d11fed57842e54e25a652cb8a428e0ace97d32f"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
