name = "lewsicraft-modpack"
author = "Noemi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf5620c7c8bed340c99662f680f6a184e51f5541a85beb1ea9c396dd4085716c"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.10", "1.21.9"]
