name = "lewsicraft-modpack"
author = "Noemi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "902644a8a09f13c5e0198a730a547e54d2cc8aa3f1186cc395e3f289176694e9"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
