name = "lewiscraft-modpack"
author = "Noemi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a11ab39f2b2fff4d381d9da85e6c2cf513975047b9427a6b96febe4f740597e1"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
