name = "lewsicraft-modpack"
author = "Noemi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c42a885ce0a999d290c61f896807a63365234361d14fe03f5ea2d167114deb27"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"
