name = "lewsicraft-modpack"
author = "Noemi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e2aee833fe4ff192623c058699b984885c891665db9343e88239c1bd457f7e3"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
